import {describe, expect, it} from "vitest";
import {stringifyConfig} from "./config-text";

describe("config text utils", () => {
    it("serializes scalar and repeatable config values", () => {
        expect(stringifyConfig({
            "font-size": 14,
            "background": "#101010",
            "window-vsync": false,
            "keybind": ["ctrl+a=select_all", "ctrl+c=copy_to_clipboard"]
        })).toBe([
            "# Config generated by Ghostty Config Studio\n",
            "font-size = 14",
            "background = #101010",
            "window-vsync = false",
            "keybind = ctrl+a=select_all",
            "keybind = ctrl+c=copy_to_clipboard"
        ].join("\n"));
    });

    it("can omit the generated header", () => {
        expect(stringifyConfig({foreground: "#ffffff"}, false)).toBe("foreground = #ffffff");
    });
});
