type ConfigValue = string | number | boolean | Array<string | number | boolean>;

export type ConfigDiff = Record<string, ConfigValue>;

export function stringifyConfig(config: ConfigDiff, includeHeader = true) {
    const lines = includeHeader ? ["# Config generated by Ghostty Config Studio\n"] : [];

    for (const key in config) {
        const value = config[key];
        if (!Array.isArray(value)) {
            lines.push(`${key} = ${value}`);
            continue;
        }

        for (const entry of value) {
            lines.push(`${key} = ${entry}`);
        }
    }

    return lines.join("\n");
}
